/*
 * This source file was generated by the Gradle 'init' task
 */
package argha.netutilx;

import argha.netutilx.model.DnsServer;
import argha.netutilx.model.DnsTypes;
import argha.netutilx.service.DnsApiService;
import java.io.IOException;
import java.util.List;

public class App {
    
    public static void main(String[] args) {
        DnsApiService service = new DnsApiService();
        System.out.println("--- Testing Netutilx API Service ---");
        try {
            System.out.println("\n [1] Fetching DNS Servers");
            List<DnsServer> dnsServers = service.getDnsServers();
            dnsServers.forEach(System.out::println);
            
            System.out.println("\n [2] Fetching DNS Types");
            List<DnsTypes> dnsTypes = service.getDnsTypes();
            dnsTypes.forEach(System.out::println);
            
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }
    }
}
